# Generated by Django 4.2.20 on 2026-08-28 08:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('required_level', models.PositiveSmallIntegerField(default=1)),
                ('cooldown_seconds', models.PositiveSmallIntegerField(default=3)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreaEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BattleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_snapshot', models.JSONField()),
                ('result', models.CharField(max_length=8)),
                ('end_reason', models.CharField(max_length=24)),
                ('rounds', models.JSONField()),
                ('rewards', models.JSONField()),
                ('random_seed', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DropEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_rate', models.DecimalField(decimal_places=6, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('min_quantity', models.PositiveSmallIntegerField(default=1)),
                ('max_quantity', models.PositiveSmallIntegerField(default=1)),
                ('drop_group', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('channel_context', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '啟用'), ('suspended', '停權')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('item_type', models.CharField(choices=[('weapon', '武器'), ('armor', '防具'), ('accessory', '飾品'), ('material', '材料')], max_length=16)),
                ('rarity', models.CharField(default='common', max_length=16)),
                ('weapon_type', models.CharField(blank=True, max_length=30)),
                ('atk_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('agility_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('required_level', models.PositiveSmallIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('max_hp', models.PositiveIntegerField()),
                ('max_mp', models.PositiveIntegerField(default=0)),
                ('atk', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('intelligence', models.PositiveIntegerField(default=0)),
                ('magic_defense', models.PositiveIntegerField(default=0)),
                ('agility', models.PositiveIntegerField(default=0)),
                ('critical', models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.5)])),
                ('exp_reward', models.PositiveIntegerField()),
                ('gold_min', models.PositiveIntegerField()),
                ('gold_max', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99)])),
                ('exp', models.PositiveBigIntegerField(default=0)),
                ('gold', models.PositiveBigIntegerField(default=0)),
                ('hp', models.PositiveIntegerField(default=30)),
                ('mp', models.PositiveIntegerField(default=10)),
                ('max_hp', models.PositiveIntegerField(default=30)),
                ('max_mp', models.PositiveIntegerField(default=10)),
                ('atk', models.PositiveIntegerField(default=8)),
                ('defense', models.PositiveIntegerField(default=3)),
                ('intelligence', models.PositiveIntegerField(default=3)),
                ('magic_defense', models.PositiveIntegerField(default=2)),
                ('agility', models.PositiveIntegerField(default=5)),
                ('critical', models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.5)])),
                ('job_count', models.PositiveSmallIntegerField(default=0)),
                ('last_battle_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game.gameaccount')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='game.job')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(max_length=30)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiencies', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='monster',
            constraint=models.CheckConstraint(check=models.Q(('gold_max__gte', models.F('gold_min'))), name='monster_gold_range_valid'),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalidentity',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='game.gameaccount'),
        ),
        migrations.AddField(
            model_name='equipmentset',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessory_users', to='game.item'),
        ),
        migrations.AddField(
            model_name='equipmentset',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='armor_users', to='game.item'),
        ),
        migrations.AddField(
            model_name='equipmentset',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='game.player'),
        ),
        migrations.AddField(
            model_name='equipmentset',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weapon_users', to='game.item'),
        ),
        migrations.AddField(
            model_name='dropentry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.item'),
        ),
        migrations.AddField(
            model_name='dropentry',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='game.monster'),
        ),
        migrations.AddField(
            model_name='battlerecord',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='game.player'),
        ),
        migrations.AddField(
            model_name='areaencounter',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='game.area'),
        ),
        migrations.AddField(
            model_name='areaencounter',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='game.monster'),
        ),
        migrations.AddConstraint(
            model_name='weaponproficiency',
            constraint=models.UniqueConstraint(fields=('player', 'weapon_type'), name='unique_weapon_proficiency'),
        ),
        migrations.AddConstraint(
            model_name='playeritem',
            constraint=models.UniqueConstraint(fields=('player', 'item'), name='unique_player_item'),
        ),
        migrations.AddConstraint(
            model_name='externalidentity',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_user_id', 'channel_context'), name='unique_external_identity'),
        ),
        migrations.AddConstraint(
            model_name='dropentry',
            constraint=models.CheckConstraint(check=models.Q(('max_quantity__gte', models.F('min_quantity'))), name='drop_quantity_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='areaencounter',
            constraint=models.UniqueConstraint(fields=('area', 'monster'), name='unique_area_monster'),
        ),
    ]
