# Generated by Django 4.2.20 on 2026-09-01 00:58

from django.db import migrations, models


def rename_legacy_content(apps, schema_editor):
    mappings = {
        "Job": {"初心者": "遊方客"},
        "Area": {"新手草原": "蘭若古道"},
        "Item": {"練習木劍": "桃木劍", "布衣": "舊道袍", "草原戒指": "狐紋古玉", "哥布林牙齒": "陰氣殘縷"},
        "Monster": {"史萊姆": "遊魂", "野狼": "狐魅", "哥布林": "畫皮鬼"},
    }
    for model_name, names in mappings.items():
        model = apps.get_model("game", model_name)
        for old_name, new_name in names.items():
            model.objects.filter(name=old_name).update(name=new_name)


def restore_legacy_content_names(apps, schema_editor):
    mappings = {
        "Job": {"遊方客": "初心者"},
        "Area": {"蘭若古道": "新手草原"},
        "Item": {"桃木劍": "練習木劍", "舊道袍": "布衣", "狐紋古玉": "草原戒指", "陰氣殘縷": "哥布林牙齒"},
        "Monster": {"遊魂": "史萊姆", "狐魅": "野狼", "畫皮鬼": "哥布林"},
    }
    for model_name, names in mappings.items():
        model = apps.get_model("game", model_name)
        for old_name, new_name in names.items():
            model.objects.filter(name=old_name).update(name=new_name)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='adaptation_type',
            field=models.CharField(choices=[('canonical', '原典'), ('adapted', '改編'), ('original', '原創')], default='original', max_length=16),
        ),
        migrations.AddField(
            model_name='area',
            name='lore_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='area',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='area',
            name='source_work',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='adaptation_type',
            field=models.CharField(choices=[('canonical', '原典'), ('adapted', '改編'), ('original', '原創')], default='original', max_length=16),
        ),
        migrations.AddField(
            model_name='item',
            name='lore_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='source_work',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='adaptation_type',
            field=models.CharField(choices=[('canonical', '原典'), ('adapted', '改編'), ('original', '原創')], default='original', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='lore_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='source_work',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='monster',
            name='adaptation_type',
            field=models.CharField(choices=[('canonical', '原典'), ('adapted', '改編'), ('original', '原創')], default='original', max_length=16),
        ),
        migrations.AddField(
            model_name='monster',
            name='lore_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='monster',
            name='source_work',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(rename_legacy_content, restore_legacy_content_names),
    ]
