# Generated by Django 4.2.20 on 2026-09-01 03:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_area_is_level_simulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_work', models.CharField(blank=True, max_length=100)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('adaptation_type', models.CharField(choices=[('canonical', '原典'), ('adapted', '改編'), ('original', '原創')], default='original', max_length=16)),
                ('lore_note', models.TextField(blank=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('mp_cost', models.PositiveSmallIntegerField()),
                ('damage_type', models.CharField(choices=[('physical', '物理'), ('magical', '魔法')], max_length=12)),
                ('power_multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('trigger_rate', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('accuracy_modifier', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('condition', models.CharField(choices=[('always', '無額外條件'), ('self_hp_lte_30', '自身 HP ≤ 30%'), ('target_hp_gte_50', '目標 HP ≥ 50%')], default='always', max_length=24)),
                ('enabled', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='game.job')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configured_skills', to='game.player')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_configurations', to='game.skill')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.CheckConstraint(check=models.Q(('trigger_rate__gte', 0), ('trigger_rate__lte', 1)), name='skill_trigger_rate_valid'),
        ),
        migrations.AddConstraint(
            model_name='playerskill',
            constraint=models.CheckConstraint(check=models.Q(('priority__gte', 1), ('priority__lte', 3)), name='player_skill_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='playerskill',
            constraint=models.UniqueConstraint(fields=('player', 'skill'), name='unique_player_skill'),
        ),
        migrations.AddConstraint(
            model_name='playerskill',
            constraint=models.UniqueConstraint(fields=('player', 'priority'), name='unique_player_skill_priority'),
        ),
    ]
