# Generated by Django 4.2.20 on 2026-09-11 06:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_job_requirements_and_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_work', models.CharField(blank=True, max_length=100)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('adaptation_type', models.CharField(choices=[('canonical', '原典'), ('adapted', '改編'), ('original', '原創')], default='original', max_length=16)),
                ('lore_note', models.TextField(blank=True)),
                ('rank', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('min_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('max_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=80)),
                ('name_en', models.CharField(max_length=120)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='game.job')),
            ],
            options={
                'ordering': ['job_id', 'rank'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.UniqueConstraint(fields=('job', 'rank'), name='unique_job_title_rank'),
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.CheckConstraint(check=models.Q(('rank__gte', 1), ('rank__lte', 7)), name='job_title_rank_range'),
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.CheckConstraint(check=models.Q(('min_level__gte', 1), ('min_level__lte', 99)), name='job_title_min_level_range'),
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.CheckConstraint(check=models.Q(('max_level__gte', 1), ('max_level__lte', 99)), name='job_title_max_level_range'),
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.CheckConstraint(check=models.Q(('max_level__gte', models.F('min_level'))), name='job_title_level_order'),
        ),
    ]
