# Generated by Django 4.2.23 on 2026-09-01 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_area_adaptation_type_area_lore_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='agility_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='atk_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='critical_bonus',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='job',
            name='defense_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='intelligence_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='magic_defense_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='max_hp_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='max_mp_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='prerequisite_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_jobs', to='game.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(0, '初始'), (1, '第一階'), (2, '第二階'), (3, '第三階')], default=0),
        ),
    ]
