# Generated by Django 4.2.23 on 2026-09-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_job_agility_bonus_job_atk_bonus_job_critical_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_level_simulation',
            field=models.BooleanField(default=False),
        ),
    ]
