export type Locale = "en" | "zh-TW";

const englishContent: Record<string, string> = {
  "冒險探索": "Adventure Exploration",
  "展開冒險之旅。": "Set out on an adventure.",
  "武者": "Warrior",
  "祝由師": "Ritual Healer",
  "夜行客": "Night Rogue",
  "山林獵手": "Wilds Hunter",
  "丹師": "Alchemist",
  "樂師": "Minstrel",
  "通靈者": "Spirit Medium",
  "神女": "Divine Maiden",
  "法主": "Arcane Hierophant",
  "仙門宗主": "Immortal Sect Master",
  "劍客": "Swordmaster",
  "行者": "Ascetic",
  "影衛": "Shadow Guard",
  "破邪斬": "Evil-Rending Slash",
  "五行符": "Five Elements Talisman",
  "祝由祓煞": "Ritual Banishment",
  "夜襲": "Night Assault",
  "伏妖箭": "Demon-Subduing Arrow",
  "丹火化形": "Elixir Flame Transmutation",
  "清商鎮魂": "Pure Melody Soulward",
  "通幽神念": "Netherworld Communion",
  "神女降魔": "Divine Demonfall",
  "萬法歸一": "Convergence of All Arts",
  "仙門敕令": "Immortal Sect Edict",
  "御劍疾斬": "Swift Flying Sword",
  "金剛伏魔": "Vajra Demon Subdual",
  "無影絕殺": "Shadowless Execution",
  "遊方客": "Wanderer",
  "金剛力士": "Vajra Guardian",
  "飛燕劍客": "Swallowblade Swordsman",
  "御靈師": "Spirit Tamer",
  "方士": "Taoist Adept",
  "護法金剛": "Dharma Vajra",
  "流雲劍俠": "Cloudflow Swordmaster",
  "通幽使": "Nether Envoy",
  "五行術士": "Five Elements Adept",
  "鎮獄神將": "Hellwarden Divine General",
  "凌霄劍仙": "Firmament Sword Immortal",
  "萬靈宗師": "Sovereign of All Spirits",
  "乾坤天師": "Cosmos Celestial Master",
  "破邪重擊": "Evil-Rending Strike",
  "金剛震": "Vajra Quake",
  "背水一擊": "Last-Stand Blow",
  "燕返": "Swallow Reversal",
  "流星趕月": "Meteor Chasing the Moon",
  "絕影一閃": "Shadowless Flash",
  "靈狐襲": "Spirit Fox Assault",
  "紙將衝陣": "Paper General Charge",
  "火符咒": "Flame Talisman",
  "五雷咒": "Five Thunder Spell",
  "鎮邪咒": "Evil-Sealing Spell",
  "護法棍": "Dharma Staff",
  "伏魔震": "Demon-Subduing Quake",
  "金剛伏魔棍": "Vajra Demon-Subduing Staff",
  "流雲十三式": "Thirteen Cloudflow Forms",
  "雲蹤斬": "Cloudtrail Slash",
  "流雲快劍": "Cloudflow Swiftblade",
  "幽冥鬼卒": "Netherworld Soldier",
  "攝魂靈獸": "Soul-Seizing Spirit Beast",
  "幽燈引魂": "Nether Lamp Soulcall",
  "五行烈焰": "Five Elements Inferno",
  "水雷法": "Water Thunder Art",
  "五行咒": "Five Elements Spell",
  "鎮獄破": "Hellwarden Breaker",
  "神將怒": "Divine General's Wrath",
  "神將戰戟": "Divine General's Halberd",
  "凌霄一劍": "Firmament Sword",
  "劍落九霄": "Swordfall from the Ninth Heaven",
  "御劍凌空": "Skyborne Swordflight",
  "萬靈朝宗": "Homage of All Spirits",
  "神將敕令": "Divine General's Edict",
  "萬靈共鳴": "Resonance of All Spirits",
  "乾坤雷劫": "Cosmic Thunder Tribulation",
  "天罡鎮煞": "Celestial Ward",
  "乾坤法印": "Cosmic Dharma Seal",
  "蘭若古道": "Ancient Lanruo Road",
  "等級模擬場": "Level Simulation Grounds",
  "通往荒寺的幽暗古道，夜行者常在此遇見狐影與遊魂。": "A shadowed old road leading to a deserted temple, where night travelers often encounter fox spirits and wandering souls.",
  "依挑戰者目前等級生成同級修行幻影，供本機戰鬥驗證使用。": "Creates a training phantom at the challenger's current level for local battle testing.",
  "桃木劍": "Peachwood Sword",
  "舊道袍": "Worn Taoist Robe",
  "狐紋古玉": "Fox-Patterned Ancient Jade",
  "陰氣殘縷": "Wisp of Yin Essence",
  "遊魂": "Wandering Soul",
  "狐魅": "Fox Enchantress",
  "畫皮鬼": "Painted-Skin Demon",
  "修行幻影": "Training Phantom",
  "未知妖物": "Unknown Creature",
  "刀": "Blade",
  "劍": "Sword",
  "槍": "Spear",
  "法劍": "Ritual Sword",
  "法杖": "Staff",
  "符器": "Talisman Focus",
  "短刃": "Dagger",
  "弓": "Bow",
  "弩": "Crossbow",
  "樂器": "Instrument",
  "拳套": "Gauntlet",
  "棍": "Staff Weapon",
};

const englishErrors: Record<string, string> = {
  "LINE 登入來源無效。": "Invalid LINE login origin.",
  "缺少 LINE ID token。": "LINE ID token is missing.",
  "LINE 登入尚未完成設定。": "LINE login has not been configured.",
  "LINE 登入憑證無效。": "Invalid LINE login credentials.",
  "角色已存在。": "A character already exists.",
  "角色名稱必須為 1 至 20 個字元。": "Character name must contain 1 to 20 characters.",
  "找不到地區。": "Area not found.",
  "材料不能裝備。": "Materials cannot be equipped.",
  "不能跳階或轉入其他職業路線。": "You cannot skip a tier or switch to another job path.",
  "目前尚未符合轉職條件。": "The job advancement requirements have not been met.",
  "目前 HP 不得超過調整後的 MaxHP。": "Current HP cannot exceed the adjusted MaxHP.",
  "等級必須介於 1 至 99。": "Level must be between 1 and 99.",
  "角色特性必須介於 1 至 99。": "Character traits must be between 1 and 99.",
  "必須提供完整的七種角色特性。": "All seven character traits are required.",
  "初始角色特性不得低於基礎值或高於 18。": "Initial traits cannot be below their base values or above 18.",
  "初始角色必須正好分配 10 點特性點數。": "Exactly 10 initial trait points must be allocated.",
  "至少一項初始角色特性必須達到 12。": "At least one initial trait must reach 12.",
  "角色特性尚未符合此職業門檻。": "The character does not meet this job's trait requirements.",
  "目前職業不能使用此武器類型。": "The current job cannot use this weapon type.",
  "目前裝備欄位包含不合法物品。": "An equipment slot contains an invalid item.",
  "目前裝備包含角色未持有的物品。": "The equipped item is not owned by this character.",
  "此地區目前沒有怪物。": "This area currently has no monsters.",
  "找不到你的角色。": "Your character could not be found.",
  "帳號目前無法進行遊戲。": "This account is currently unable to play.",
  "角色目前無法戰鬥。": "This character is currently unable to battle.",
  "此區域只在本機開發環境開放。": "This area is available only in the local development environment.",
  "角色等級不足，無法進入此地區。": "Your character level is too low to enter this area.",
  "Not found.": "Not found.",
};

const chinesePattern = /[\u3400-\u9fff]/;

export function contentText(value: unknown, locale: Locale): string {
  const text = String(value ?? "");
  if (locale === "zh-TW") return text;
  return englishContent[text] ?? (chinesePattern.test(text) ? "Untranslated game content" : text);
}

export function errorMessage(value: unknown, locale: Locale): string | null {
  if (typeof value !== "string" || !value) return null;
  if (locale === "zh-TW") return value;
  const cooldown = value.match(/^請等待 ([0-9.]+) 秒後再戰鬥。$/);
  if (cooldown) return `Please wait ${cooldown[1]} seconds before battling again.`;
  return englishErrors[value] ?? (chinesePattern.test(value) ? "The request could not be completed." : value);
}
